name: 部署到GitHub Pages

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: 检出代码
              uses: actions/checkout@v3

            - name: 设置Node.js环境
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"

            - name: 安装依赖
              run: npm ci

            - name: 构建项目
              run: |
                  echo "sitemp.misssu.cn" > ./public/CNAME
                  npm run build --base=/

            - name: 部署到GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
                  cname: sitemp.misssu.cn
