name: 部署到GitHub Pages

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 检出代码
              uses: actions/checkout@v3

            - name: 设置Node.js环境
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"

            - name: 安装依赖
              run: npm ci

            - name: 构建项目
              run: npm run build

            - name: 设置Pages
              uses: actions/configure-pages@v3

            - name: 上传artifacts
              uses: actions/upload-pages-artifact@v1
              with:
                  path: "./dist"

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: 部署到GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
